In [2]:
pip install opencv-python

In [1]:
import cv2

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from skimage import io
from PIL import Image
from matplotlib.pyplot import imshow
import cv2 as cv


# Read Image

In [3]:
image = cv.imread('artificial-intelligence-current-state.webp')

In [4]:
image

array([[[134, 130, 129],
        [134, 130, 129],
        [134, 130, 129],
        ...,
        [131, 128, 131],
        [131, 128, 131],
        [131, 128, 131]],

       [[  6,   2,   1],
        [  6,   2,   1],
        [  6,   2,   1],
        ...,
        [  3,   0,   3],
        [  3,   0,   3],
        [  3,   0,   3]],

       [[ 10,   6,   4],
        [ 10,   6,   4],
        [ 10,   6,   4],
        ...,
        [  7,   3,   6],
        [  7,   3,   6],
        [  7,   3,   6]],

       ...,

       [[  3,   3,   3],
        [  3,   3,   3],
        [  3,   3,   3],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  7,   7,   7],
        [  7,   7,   7],
        [  7,   7,   7]],

       [[128, 128, 128],
        [128, 128, 128],
        [128, 128, 128],
        ...,
        [126, 126, 126],
        [126, 126, 126],
        [126, 126, 126]]

In [6]:
cv2.imshow("result",image)

In [12]:
from IPython.display import display, clear_output

# convert color from CV2 BGR back to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
display(image)

array([[[134, 130, 129],
        [134, 130, 129],
        [134, 130, 129],
        ...,
        [131, 128, 131],
        [131, 128, 131],
        [131, 128, 131]],

       [[  6,   2,   1],
        [  6,   2,   1],
        [  6,   2,   1],
        ...,
        [  3,   0,   3],
        [  3,   0,   3],
        [  3,   0,   3]],

       [[ 10,   6,   4],
        [ 10,   6,   4],
        [ 10,   6,   4],
        ...,
        [  7,   3,   6],
        [  7,   3,   6],
        [  7,   3,   6]],

       ...,

       [[  3,   3,   3],
        [  3,   3,   3],
        [  3,   3,   3],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  7,   7,   7],
        [  7,   7,   7],
        [  7,   7,   7]],

       [[128, 128, 128],
        [128, 128, 128],
        [128, 128, 128],
        ...,
        [126, 126, 126],
        [126, 126, 126],
        [126, 126, 126]]

In [9]:
url = "https://iiif.lib.ncsu.edu/iiif/0052574/full/800,/0/default.jpg"
im = io.imread(url)

In [11]:
im

array([[[ 89, 151, 212],
        [ 92, 154, 213],
        [ 94, 156, 215],
        ...,
        [ 48, 117, 176],
        [ 47, 116, 175],
        [ 45, 114, 173]],

       [[ 91, 153, 214],
        [ 92, 154, 213],
        [ 92, 154, 213],
        ...,
        [ 47, 116, 175],
        [ 46, 115, 174],
        [ 45, 114, 173]],

       [[ 90, 152, 213],
        [ 91, 153, 212],
        [ 90, 152, 211],
        ...,
        [ 48, 114, 174],
        [ 48, 114, 174],
        [ 48, 114, 174]],

       ...,

       [[160, 132, 120],
        [167, 145, 122],
        [176, 159, 133],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[157, 129, 117],
        [167, 145, 124],
        [170, 154, 128],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[148, 122, 109],
        [161, 139, 118],
        [163, 147, 122],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]